/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'payload-users': PayloadUserAuthOperations;
  };
  blocks: {};
  collections: {
    'payload-users': PayloadUser;
    'nav-nodes': NavNode;
    'help-docs': HelpDoc;
    'support-docs': SupportDoc;
    'trust-docs': TrustDoc;
    'legal-docs': LegalDoc;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'payload-users': PayloadUsersSelect<false> | PayloadUsersSelect<true>;
    'nav-nodes': NavNodesSelect<false> | NavNodesSelect<true>;
    'help-docs': HelpDocsSelect<false> | HelpDocsSelect<true>;
    'support-docs': SupportDocsSelect<false> | SupportDocsSelect<true>;
    'trust-docs': TrustDocsSelect<false> | TrustDocsSelect<true>;
    'legal-docs': LegalDocsSelect<false> | LegalDocsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: PayloadUser;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface PayloadUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-users".
 */
export interface PayloadUser {
  id: number;
  roles?: ('admin' | 'editor' | 'trust-reviewer' | 'legal-reviewer' | 'migrator')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'payload-users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav-nodes".
 */
export interface NavNode {
  id: number;
  /**
   * Display name shown in the sidebar.
   */
  label: string;
  /**
   * URL segment for this node (kebab-case). Combined with parent slugs to form the full path.
   */
  slug: string;
  /**
   * Short description shown on section landing pages.
   */
  blurb?: string | null;
  /**
   * Leave blank for top-level nodes (root sections).
   */
  parent?: (number | null) | NavNode;
  /**
   * For leaf nodes: pick the document this route renders. Leave blank for branches.
   */
  doc?:
    | ({
        relationTo: 'help-docs';
        value: number | HelpDoc;
      } | null)
    | ({
        relationTo: 'support-docs';
        value: number | SupportDoc;
      } | null)
    | ({
        relationTo: 'trust-docs';
        value: number | TrustDoc;
      } | null)
    | ({
        relationTo: 'legal-docs';
        value: number | LegalDoc;
      } | null);
  /**
   * Lower numbers sort first within the same parent.
   */
  order?: number | null;
  /**
   * Check for top-level pillars (Help Center, Support, Trust, Legal). Drives the sidebar root.
   */
  rootSection?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "help-docs".
 */
export interface HelpDoc {
  id: number;
  /**
   * Display title shown as the page <h1> and in the sidebar.
   */
  title: string;
  /**
   * Canonical route, e.g. /resources/help-center/getting-started/what-is-musicosy. MUST match the nav node's derived path.
   */
  path: string;
  /**
   * Short description used in nav node cards and meta tags. Optional — falls back to title.
   */
  blurb?: string | null;
  /**
   * Article body, top-to-bottom. Drag to reorder. Use the 6 block types only — do not request new ones without architectural review.
   */
  blocks?:
    | (
        | {
            /**
             * Standard paragraph text.
             */
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
        | {
            text: string;
            /**
             * H2 = section heading, H3 = sub-section. Defaults to H2.
             */
            level?: ('2' | '3') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heading';
          }
        | {
            /**
             * Check for numbered lists, uncheck for bulleted.
             */
            ordered?: boolean | null;
            items: {
              /**
               * e.g. 'Discover culture:' — rendered bold before the text.
               */
              lead?: string | null;
              text: string;
              /**
               * Indented sub-bullets rendered under this item.
               */
              children?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'list';
          }
        | {
            variant?: ('note' | 'warning') | null;
            /**
             * Small bold label shown above the callout text.
             */
            title?: string | null;
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callout';
          }
        | {
            headers: {
              value: string;
              id?: string | null;
            }[];
            /**
             * Each row should have the same number of cells as there are headers.
             */
            rows: {
              cells: {
                value: string;
                id?: string | null;
              }[];
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'table';
          }
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
      )[]
    | null;
  /**
   * Linked at the bottom of the article.
   */
  related?:
    | (
        | {
            relationTo: 'help-docs';
            value: number | HelpDoc;
          }
        | {
            relationTo: 'support-docs';
            value: number | SupportDoc;
          }
        | {
            relationTo: 'trust-docs';
            value: number | TrustDoc;
          }
        | {
            relationTo: 'legal-docs';
            value: number | LegalDoc;
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-docs".
 */
export interface SupportDoc {
  id: number;
  title: string;
  /**
   * Canonical route, e.g. /support/account-and-access/sign-in.
   */
  path: string;
  blurb?: string | null;
  category?:
    | ('account-and-access' | 'reports-and-appeals' | 'payments-and-purchases' | 'technical-support' | 'contact-us')
    | null;
  blocks?:
    | (
        | {
            /**
             * Standard paragraph text.
             */
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
        | {
            text: string;
            /**
             * H2 = section heading, H3 = sub-section. Defaults to H2.
             */
            level?: ('2' | '3') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heading';
          }
        | {
            /**
             * Check for numbered lists, uncheck for bulleted.
             */
            ordered?: boolean | null;
            items: {
              /**
               * e.g. 'Discover culture:' — rendered bold before the text.
               */
              lead?: string | null;
              text: string;
              /**
               * Indented sub-bullets rendered under this item.
               */
              children?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'list';
          }
        | {
            variant?: ('note' | 'warning') | null;
            /**
             * Small bold label shown above the callout text.
             */
            title?: string | null;
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callout';
          }
        | {
            headers: {
              value: string;
              id?: string | null;
            }[];
            /**
             * Each row should have the same number of cells as there are headers.
             */
            rows: {
              cells: {
                value: string;
                id?: string | null;
              }[];
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'table';
          }
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
      )[]
    | null;
  related?:
    | (
        | {
            relationTo: 'help-docs';
            value: number | HelpDoc;
          }
        | {
            relationTo: 'support-docs';
            value: number | SupportDoc;
          }
        | {
            relationTo: 'trust-docs';
            value: number | TrustDoc;
          }
        | {
            relationTo: 'legal-docs';
            value: number | LegalDoc;
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trust-docs".
 */
export interface TrustDoc {
  id: number;
  title: string;
  /**
   * Canonical route, e.g. /privacy-and-safety/safety-and-security/account-security.
   */
  path: string;
  blurb?: string | null;
  /**
   * Name/ID of the reviewer who approved this doc for publication. REQUIRED before publishing.
   */
  approvedBy?: string | null;
  approvedAt?: string | null;
  blocks?:
    | (
        | {
            /**
             * Standard paragraph text.
             */
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
        | {
            text: string;
            /**
             * H2 = section heading, H3 = sub-section. Defaults to H2.
             */
            level?: ('2' | '3') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heading';
          }
        | {
            /**
             * Check for numbered lists, uncheck for bulleted.
             */
            ordered?: boolean | null;
            items: {
              /**
               * e.g. 'Discover culture:' — rendered bold before the text.
               */
              lead?: string | null;
              text: string;
              /**
               * Indented sub-bullets rendered under this item.
               */
              children?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'list';
          }
        | {
            variant?: ('note' | 'warning') | null;
            /**
             * Small bold label shown above the callout text.
             */
            title?: string | null;
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callout';
          }
        | {
            headers: {
              value: string;
              id?: string | null;
            }[];
            /**
             * Each row should have the same number of cells as there are headers.
             */
            rows: {
              cells: {
                value: string;
                id?: string | null;
              }[];
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'table';
          }
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
      )[]
    | null;
  related?:
    | (
        | {
            relationTo: 'help-docs';
            value: number | HelpDoc;
          }
        | {
            relationTo: 'support-docs';
            value: number | SupportDoc;
          }
        | {
            relationTo: 'trust-docs';
            value: number | TrustDoc;
          }
        | {
            relationTo: 'legal-docs';
            value: number | LegalDoc;
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-docs".
 */
export interface LegalDoc {
  id: number;
  title: string;
  /**
   * Canonical route, e.g. /legal-and-policies/terms-of-use. The site always serves the currently-effective version at this path.
   */
  path: string;
  blurb?: string | null;
  /**
   * Semantic version, e.g. '2.1'. Increment when publishing changes that legally supersede the prior version.
   */
  version?: string | null;
  /**
   * Date this version takes effect.
   */
  effectiveDate: string;
  /**
   * If this version has been replaced, link to the newer version here. Leave blank for the current version.
   */
  supersededBy?: (number | null) | LegalDoc;
  status?: ('draft' | 'effective' | 'archived') | null;
  /**
   * Legal reviewer name. REQUIRED before a doc can move to 'effective' status.
   */
  approvedBy?: string | null;
  blocks?:
    | (
        | {
            /**
             * Standard paragraph text.
             */
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
        | {
            text: string;
            /**
             * H2 = section heading, H3 = sub-section. Defaults to H2.
             */
            level?: ('2' | '3') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heading';
          }
        | {
            /**
             * Check for numbered lists, uncheck for bulleted.
             */
            ordered?: boolean | null;
            items: {
              /**
               * e.g. 'Discover culture:' — rendered bold before the text.
               */
              lead?: string | null;
              text: string;
              /**
               * Indented sub-bullets rendered under this item.
               */
              children?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'list';
          }
        | {
            variant?: ('note' | 'warning') | null;
            /**
             * Small bold label shown above the callout text.
             */
            title?: string | null;
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callout';
          }
        | {
            headers: {
              value: string;
              id?: string | null;
            }[];
            /**
             * Each row should have the same number of cells as there are headers.
             */
            rows: {
              cells: {
                value: string;
                id?: string | null;
              }[];
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'table';
          }
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
      )[]
    | null;
  related?:
    | (
        | {
            relationTo: 'help-docs';
            value: number | HelpDoc;
          }
        | {
            relationTo: 'support-docs';
            value: number | SupportDoc;
          }
        | {
            relationTo: 'trust-docs';
            value: number | TrustDoc;
          }
        | {
            relationTo: 'legal-docs';
            value: number | LegalDoc;
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'payload-users';
        value: number | PayloadUser;
      } | null)
    | ({
        relationTo: 'nav-nodes';
        value: number | NavNode;
      } | null)
    | ({
        relationTo: 'help-docs';
        value: number | HelpDoc;
      } | null)
    | ({
        relationTo: 'support-docs';
        value: number | SupportDoc;
      } | null)
    | ({
        relationTo: 'trust-docs';
        value: number | TrustDoc;
      } | null)
    | ({
        relationTo: 'legal-docs';
        value: number | LegalDoc;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'payload-users';
    value: number | PayloadUser;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'payload-users';
    value: number | PayloadUser;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-users_select".
 */
export interface PayloadUsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav-nodes_select".
 */
export interface NavNodesSelect<T extends boolean = true> {
  label?: T;
  slug?: T;
  blurb?: T;
  parent?: T;
  doc?: T;
  order?: T;
  rootSection?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "help-docs_select".
 */
export interface HelpDocsSelect<T extends boolean = true> {
  title?: T;
  path?: T;
  blurb?: T;
  blocks?:
    | T
    | {
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        heading?:
          | T
          | {
              text?: T;
              level?: T;
              id?: T;
              blockName?: T;
            };
        list?:
          | T
          | {
              ordered?: T;
              items?:
                | T
                | {
                    lead?: T;
                    text?: T;
                    children?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              variant?: T;
              title?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        table?:
          | T
          | {
              headers?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              rows?:
                | T
                | {
                    cells?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
      };
  related?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-docs_select".
 */
export interface SupportDocsSelect<T extends boolean = true> {
  title?: T;
  path?: T;
  blurb?: T;
  category?: T;
  blocks?:
    | T
    | {
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        heading?:
          | T
          | {
              text?: T;
              level?: T;
              id?: T;
              blockName?: T;
            };
        list?:
          | T
          | {
              ordered?: T;
              items?:
                | T
                | {
                    lead?: T;
                    text?: T;
                    children?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              variant?: T;
              title?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        table?:
          | T
          | {
              headers?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              rows?:
                | T
                | {
                    cells?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
      };
  related?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trust-docs_select".
 */
export interface TrustDocsSelect<T extends boolean = true> {
  title?: T;
  path?: T;
  blurb?: T;
  approvedBy?: T;
  approvedAt?: T;
  blocks?:
    | T
    | {
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        heading?:
          | T
          | {
              text?: T;
              level?: T;
              id?: T;
              blockName?: T;
            };
        list?:
          | T
          | {
              ordered?: T;
              items?:
                | T
                | {
                    lead?: T;
                    text?: T;
                    children?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              variant?: T;
              title?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        table?:
          | T
          | {
              headers?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              rows?:
                | T
                | {
                    cells?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
      };
  related?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-docs_select".
 */
export interface LegalDocsSelect<T extends boolean = true> {
  title?: T;
  path?: T;
  blurb?: T;
  version?: T;
  effectiveDate?: T;
  supersededBy?: T;
  status?: T;
  approvedBy?: T;
  blocks?:
    | T
    | {
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        heading?:
          | T
          | {
              text?: T;
              level?: T;
              id?: T;
              blockName?: T;
            };
        list?:
          | T
          | {
              ordered?: T;
              items?:
                | T
                | {
                    lead?: T;
                    text?: T;
                    children?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              variant?: T;
              title?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        table?:
          | T
          | {
              headers?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              rows?:
                | T
                | {
                    cells?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
      };
  related?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}